apiVersion: v1
kind: ConfigMap
metadata:
  name: espocrm-config
data:
  config.php: |
    <?php
    return [
        'database' => [
            'host' => getenv('MYSQL_HOST'),
            'dbname' => getenv('MYSQL_DATABASE'),
            'user' => getenv('MYSQL_USER'),
            'password' => getenv('MYSQL_PASSWORD'),
        ],
        'useCache' => true,
        'siteUrl' => 'https://your-domain.com',
    ];