apiVersion: v1
kind: Secret
metadata:
  name: espocrm-secrets
type: Opaque
stringData:
  mysql-host: "cloudsql-proxy"
  mysql-database: "espocrm"
  mysql-user: "espouser"
  mysql-password: "StrongPassword123!"